name: CI

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: pre-commit/action@v3.0.1

  tests:
    name: Run tests (${{ matrix.tox-env }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tox-env: type
          - tox-env: 2024_11
          - tox-env: 2024_12
          - tox-env: 2025_1
          - tox-env: 2025_2
          - tox-env: 2025_4
          - tox-env: 2025_5
          - tox-env: 2025_6
          - tox-env: 2025_7
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Load tox cache
        uses: actions/cache@v4
        with:
          path: |
            .venv
            .tox
          key: env-${{ hashFiles(format('tests/env/{0}/uv.lock', matrix.tox-env )) }}-${{ matrix.tox-env }}

      - name: Install dependencies
        run: uv sync --only-group tox

      - name: Run tests
        run: uv run tox -e ${{ matrix.tox-env }}

  validate:
    name: Validate for HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands
